[build-system]
requires = ["setuptools>=61.0", "networkx"]
build-backend = "setuptools.build_meta"

[project]
name = "skywing"
version = "1.0"
description = "A high-reliability, real-time, decentralized platform for collaborative autonomy."
maintainers = [
  { name = "Tom Benson", email = "benson31@llnl.gov" },
  { name = "Shayna Kapadia", email = "kapadia2@llnl.gov" },
  { name = "Annika Mauro", email = "mauro3@llnl.gov" },
  { name = "Wayne Mitchell", email = "mitchell82@llnl.gov" },
  { name = "Sarah Osborn", email = "osborn9@llnl.gov" },
  { name = "Colin Ponce", email = "ponce11@llnl.gov" },
]
authors = [
  { name = "Tom Benson", email = "benson31@llnl.gov" },
  { name = "Michael Brzustowicz", email = "brzustowicz1@llnl.gov" },
  { name = "Aly Fox", email = "fox33@llnl.gov" },
  { name = "Kendall Harter", email = "harter8@llnl.gov" },
  { name = "Shayna Kapadia", email = "kapadia2@llnl.gov" },
  { name = "Annika Mauro", email = "mauro3@llnl.gov" },
  { name = "Wayne Mitchell", email = "mitchell82@llnl.gov" },
  { name = "Sarah Osborn", email = "osborn9@llnl.gov" },
  { name = "Colin Ponce", email = "ponce11@llnl.gov" },
  { name = "Rachel Waldon", email = "waldon1@llnl.gov" },
]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 3 - Alpha",

  "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",  "Operating System :: MacOS",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Software Development :: Libraries",
  "Topic :: System :: Distributed Computing",
  "Private :: Do Not Upload"
]
dependencies=[
  "numpy", # Just for the example, but why not?
  "matplotlib", # For plotting scripts
  "networkx", # For topology_gen.py
  "scipy", # For topology_gen.py
  "pandas",
  "sphinx", # docs
  "pydata-sphinx-theme",
  "loguru", # For logging
  "pydantic",
  "msgpack"
]

[project.optional-dependencies]
test = ["pytest", "pytest-mock"]
dev = ["ruff>=0.3.0","basedpyright"]

[project.scripts]
skywing_drive = "skywing.drivers.driver:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest]
minversion = "9.0"
testpaths = [
    "src/tests",
]

[tool.ruff]
line-length = 88
target-version = "py39"

[tool.ruff.lint]
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "I",   # import sorting
  "B",   # flake8-bugbear
  "UP",  # pyupgrade
#  "C",   # flake8-comprehensions
#  "D",   # pydocstyle
# "SIM", # flake8-simplify
#  "TCH", # flake8-type-checking
#  "RUF", # Ruff-specific rules
#  "N",   # pep8-naming
#  "A",   # flake8-builtins
#  "ERA", # eradicate
#  "PL",  # Pylint
#  "W",   # pycodestyle warnings
]
ignore = [
  "E501",  # Line too long
  "D100",  # Missing docstring in public module
  "D104",  # Missing docstring in public package
  "D203",  # 1 blank line required before class docstring
  "D213",  # Multi-line docstring summary should start at the second line
]
exclude = [
  ".git",
  ".venv",
  "__pycache__",
  "build",
  "dist",
  ".vscode",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false

[tool.basedpyright]
include = ["src"]
exclude = [
  "**/node_modules",
  "**/__pycache__",
  "build",
  "dist",
]
pythonVersion = "3.10"
typeCheckingMode = "basic"
reportAttributeAccessIssue = false
reportMissingImports = false
