import os
import time

import numpy as np
from skywing.core.agent_cpp import AgentCpp
from skywing.drivers.utils.argparse_utils import (
    argparse_list_to_kwargs,
    parse_driver_command_line,
)
from skywing.drivers.utils.data_loaders import CSVDataLoader
from skywing.mid.cpp_iteration import CppIteration_CppProc
from skywing.mid.idempotent_processor import MaxProcessor
from skywing.mid.iteration_cpp_core import IterationCppCore
from skywing.skywing_bind_interface import CppIterationSumScalar


def main():
    # Parse the command line generated by the driver and generate the kwargs dictionary
    args = parse_driver_command_line()
    kwargs = argparse_list_to_kwargs(args.kwargs)
    num_calls = kwargs.get("num_calls", 40)
    sleep_time = kwargs.get("sleep_time", 0.1)
    update_freq = kwargs.get("update_freq", 10)

    # Get the data_file, and output_file, if provided
    data_file = kwargs.get("data_file", None)
    output_dir = kwargs.get("output_dir", None)
    output_file = None
    if output_dir:
        output_file = os.path.join(output_dir, f"output_{args.agent_id}.npy")

    # Setup the Skywing agent
    skywing_agent = AgentCpp("127.0.0.1", args.port)
    if args.nbr_ports is not None:
        nbrs = [("127.0.0.1", p) for p in args.nbr_ports]
        skywing_agent.configure_neighbors(nbrs)

    # Setup the data generator/loader
    if data_file is not None and args.agent_id is not None:
        # User gets to use whatever data format they want, as long as they define a data reader
        data_loader = CSVDataLoader(data_file, args.agent_id)
    else:

        def data_loader():
            return np.random.rand()

    input_data = data_loader()

    # Build and launch the max iteration (using C++ core backend)
    max_iteration = IterationCppCore(MaxProcessor(input_data), skywing_agent)
    max_iteration.launch()

    sum_iteration = CppIteration_CppProc(CppIterationSumScalar, skywing_agent)
    is_smaller_than_max = 0
    sum_iteration.launch(is_smaller_than_max, timeout=70)

    # Print column labels
    col_width = 12
    labels = ["Input Data", "Max Result", "< Hist. Max", "Total < Max"]
    print("".join(f"{label:>{col_width}}" for label in labels))

    # Periodically query and update the iteration
    time.sleep(sleep_time)
    # Execution loop: periodically query the result and update the data
    all_results = []
    for call in range(1, num_calls + 1):
        # Goal: Produce an output from one iteration that influences a second iteration.

        # Here, sum up how many agents have `input_data` smaller than the current max.
        max_result = max_iteration.query()
        smaller_than_max = input_data < max_result

        # The summation counts the number of `input_data` values below the current max
        sum_iteration.update_data(smaller_than_max)
        sum_result = sum_iteration.query()

        data = [input_data, max_result, smaller_than_max, sum_result]
        print("".join(f"{d:{col_width}.2g}" for d in data))

        # Grab the last result before updating the data to save to file
        if call % update_freq == update_freq - 1:
            all_results.append(sum_result)

        if call < num_calls:
            if call % update_freq == 0:
                input_data = data_loader()
                time.sleep(sleep_time)
                max_iteration.update_data(input_data)
            time.sleep(sleep_time)

        # Wait between queries
        time.sleep(sleep_time)

    # Save output to file
    if output_file:
        all_results = np.array(all_results)
        np.save(output_file, all_results)


if __name__ == "__main__":
    main()
