import os
import time

import numpy as np
from skywing.core.agent_cpp import AgentCpp
from skywing.drivers.utils.argparse_utils import (
    argparse_list_to_kwargs,
    parse_driver_command_line,
)

# WM: todo - do something more interesting with this example...


class MyPyJob:
    def __init__(self, value, agent, num_iters=10):
        self.value = value + agent.port
        self.num_iters = num_iters
        self.agent = agent

    def run(self, job_handle):
        my_tag = "value_" + str(self.agent.port)
        nbr_tags = ["value_" + str(nbr.port) for nbr in self.agent.nbrs]
        nbr_values = {}

        job_handle.declare_publication_intent(my_tag)
        for nbr_tag in nbr_tags:
            job_handle.subscribe(nbr_tag)

        for _i in range(self.num_iters):
            job_handle.publish(my_tag, ([], [], [self.value]))

            for t in nbr_tags:
                if job_handle.has_data(t):
                    nbr_values[t] = job_handle.get_data_if_present(t)

            print(f"My value: {self.value}")
            for k, v in nbr_values.items():
                print(f"Tag {k}: {v}")
            time.sleep(1)


def run_agent(
    port,
    nbr_ports,
    output_file=None,
    data_file=None,
    agent_number=None,
    num_calls=40,
    sleep_time=0.25,
):

    # Setup the Skywing agent
    skywing_agent = AgentCpp("127.0.0.1", args.port)
    if args.nbr_ports is not None:
        nbrs = [("127.0.0.1", p) for p in args.nbr_ports]
        skywing_agent.configure_neighbors(nbrs)

    mypyjob = MyPyJob(42, skywing_agent)
    skywing_agent.submit_job("mypyjob", mypyjob)

    skywing_agent.launch()
    num_calls = 0
    all_results = []
    while num_calls < 20:
        print(f"Waiting on call {num_calls}")
        num_calls += 1
        all_results.append(num_calls)
        time.sleep(sleep_time)

    # Save output to file
    if output_file:
        all_results = np.array(all_results)
        np.save(output_file, all_results)


if __name__ == "__main__":
    # Parse the command line generated by the driver and generate the kwargs dictionary
    args = parse_driver_command_line()
    kwargs = argparse_list_to_kwargs(args.kwargs)
    data_file = kwargs.get("data_file", None)
    output_dir = kwargs.get("output_dir", None)
    output_file = None
    if output_dir:
        output_file = os.path.join(output_dir, f"output_{args.agent_id}.npy")

    run_agent(
        port=args.port,
        nbr_ports=args.nbr_ports,
        output_file=output_file,
        data_file=data_file,
        agent_number=args.agent_id,
    )
