# This script defines a Skywing agent that performs distributed sum computations using neighboring agents over specified ports.
# It supports randomized data or CSV data loading per agent number, runs iterations with the CppIterationSumScalar operator, and optionally logs results to a file.
# The agent configuration and runtime parameters such as ports, data files, and output logging are configurable via command line arguments.

import os
import time

import numpy as np
from skywing.core.agent_cpp import AgentCpp
from skywing.drivers.utils.argparse_utils import (
    argparse_list_to_kwargs,
    parse_driver_command_line,
)
from skywing.drivers.utils.data_loaders import CSVDataLoader
from skywing.mid.cpp_iteration import CppIteration_CppProc
from skywing.skywing_bind_interface import CppIterationSumScalar


def main():
    # Parse the command line generated by the driver and generate the kwargs dictionary
    args = parse_driver_command_line()
    kwargs = argparse_list_to_kwargs(args.kwargs)
    num_calls = kwargs.get("num_calls", 4)
    sleep_time = kwargs.get("sleep_time", 2.0)
    update_freq = kwargs.get("update_freq", 1)

    # Get the data_file, and output_file, if provided
    data_file = kwargs.get("data_file", None)
    output_dir = kwargs.get("output_dir", None)
    output_file = None
    if output_dir:
        output_file = os.path.join(output_dir, f"output_{args.agent_id}.npy")

    # Setup the Skywing agent
    skywing_agent = AgentCpp("127.0.0.1", args.port)
    if args.nbr_ports is not None:
        nbrs = [("127.0.0.1", p) for p in args.nbr_ports]
        skywing_agent.configure_neighbors(nbrs)

    # Setup the data generator/loader
    if data_file is not None and args.agent_id is not None:
        # User gets to use whatever data format they want, as long as they define a data reader
        data_loader = CSVDataLoader(data_file, args.agent_id)
    else:

        def data_loader():
            return np.random.rand()

    skywing_iteration = CppIteration_CppProc(CppIterationSumScalar, skywing_agent)

    data = data_loader()
    print(data)
    skywing_iteration.launch(data, timeout=15)
    time.sleep(sleep_time)

    # Execution loop: periodically query the result and update the data
    all_results = []
    for call in range(1, num_calls + 1):
        result = skywing_iteration.query()
        print(f"On call {call}")
        print(f"   Data: {data}")
        print(f"   Result: {result}")

        # Grab the last result before updating the data to save to file
        if call % update_freq == update_freq - 1:
            all_results.append(result)

        if call < num_calls:
            if call % update_freq == 0:
                data = data_loader()
                time.sleep(sleep_time)
                skywing_iteration.update_data(data)
            time.sleep(sleep_time)

    # Save output to file
    if output_file:
        all_results = np.array(all_results)
        np.save(output_file, all_results)


if __name__ == "__main__":
    main()
