version: '3.5'
services:

###########################
## Core Build
###########################

  Skywing: # Working 
    container_name: skywing_env
    image: empyreanlattice/skywing
    build:
      context: ../../
      dockerfile: ./docker/Dockerfile.skywing
    network_mode: host
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: /bin/bash

