version: '3.5'
services:

##########################################################################################################################################################################################
## Core
##########################################################################################################################################################################################

  skywing: # Not Tested
    container_name: skywing
    image: empyreanlattice/skywing
    build:
      context: ../
      dockerfile: docker/Dockerfile.skywing
    network_mode: host
    restart: unless-stopped
    # command:
    