import os
import time

import numpy as np
from loguru import logger

from skywing.core import Agent
from skywing.drivers.utils.argparse_utils import (
    argparse_list_to_kwargs,
    parse_driver_command_line,
)
from skywing.drivers.utils.data_loaders import (
    CSVDataLoader,
    RandomScalarLoader,
)
from skywing.mid import Iteration, MaxProcessor


def main():
    # Parse the command line generated by the driver and generate the kwargs dictionary
    args = parse_driver_command_line()
    kwargs = argparse_list_to_kwargs(args.kwargs)

    # Number of data updates (0 corresponds to a single data point)
    num_data_updates = kwargs.get("num_data_updates", 3)
    # How often to update the data (in the case of a single
    # data point, update_freq is the total runtime)
    update_freq = kwargs.get("update_freq", 2.0)
    # How often to print current data/result to screen
    print_freq = kwargs.get("print_freq", 0.5)
    # The maximum staggering between agents, that is the
    # time between when the first agent starts and the last
    # agent starts (needed to ensure results are read at the
    # appropriate time between data updates).
    kwargs.get("max_stagger", 0.1)

    # Get the data_file and output_dir, if provided
    data_file = kwargs.get("data_file", None)
    output_dir = kwargs.get("output_dir", None)
    output_file = None
    if output_dir:
        output_file = os.path.join(output_dir, f"output_{args.agent_id}.npy")

    # Read or generate data (scalar values only for this example)
    if data_file:
        data_loader = CSVDataLoader(data_file, args.agent_id)
    else:
        data_loader = RandomScalarLoader()

    local_value = data_loader()

    # Create the Skywing agent
    agent = Agent(args.address, args.port)

    # Configure neighbors
    neighbors = [(addr, port) for addr, port in zip(args.nbr_addresses, args.nbr_ports)]
    agent.configure_neighbors(neighbors)

    # Create max processor with local value
    max_processor = MaxProcessor(local_value)
    max_iteration = Iteration(max_processor, agent)
    max_iteration.launch()

    # Create distance processor (starts at 0, will be updated)
    distance_processor = MaxProcessor(0.0)
    distance_iteration = Iteration(distance_processor, agent)
    distance_iteration.launch()

    # Wait for initial convergence
    time.sleep(0.5)

    # Track current local value (starts with initial value)
    current_local_value = local_value

    distance_from_max = 0.0
    range_value = 0.0
    all_results = []

    # Calculate total number of print cycles needed
    # Each update cycle has update_freq/print_freq prints
    num_prints_per_update = int(update_freq / print_freq)
    total_prints = num_data_updates * num_prints_per_update

    for query_num in range(total_prints):
        time.sleep(print_freq)

        # Update local value at the start of each update cycle
        update_cycle = query_num // num_prints_per_update
        if (
            query_num > 0
            and query_num % num_prints_per_update == 0
            and update_cycle <= num_data_updates
        ):
            current_local_value = data_loader()
            max_iteration.update_data(current_local_value)

        # Query the current maximum
        max_result = max_iteration.query()

        # Calculate this agent's distance from the max
        distance_from_max = max_result - current_local_value

        # Update the distance iteration with the new distance
        distance_iteration.update_data(distance_from_max)
        time.sleep(0.1)
        # Query the maximum distance (current estimate of the range)
        range_value = distance_iteration.query()

        print(
            f"{args.port:<8} {query_num:<8} {current_local_value:<12.2f} {max_result:<12.2f} {distance_from_max:<12.2f} "
            f"{range_value:<12.2f}"
        )

        # Store results at the end of each update cycle (before data updates)
        # This matches the pattern: save result max_stagger before next update
        if (query_num + 1) % num_prints_per_update == 0 and len(
            all_results
        ) < num_data_updates:
            all_results.append(range_value)

    # Save output to file
    if output_file:
        all_results_array = np.array(all_results)
        np.save(output_file, all_results_array)
        logger.info(f"Results saved to {output_file}")


if __name__ == "__main__":
    main()
