import os
import time

import numpy as np
from loguru import logger

from skywing.drivers.utils.agent_utils import (
    create_skywing_agent,
)
from skywing.drivers.utils.argparse_utils import (
    argparse_list_to_kwargs,
    parse_driver_command_line,
)
from skywing.drivers.utils.data_loaders import (
    CSVDataLoader,
    LinearSystemDataLoader,
    RandomMatrixLoader,
    RandomScalarLoader,
    RandomVectorLoader,
)
from skywing.drivers.utils.matrix_gen import matrix_gen

# WM: do we want a general include that gives us all the processors?
from skywing.mid.admm_processor import ADMMProcessor
from skywing.mid.cola_processor import COLAProcessor
from skywing.mid.count_processor import CountProcessor
from skywing.mid.idempotent_processor import MaxProcessor, MinProcessor
from skywing.mid.iteration import Iteration
from skywing.mid.jacobi_processor import JacobiProcessor
from skywing.mid.push_sum_processor import PushSumProcessor
from skywing.mid.sgd_processor import SGDProcessor
from skywing.mid.simple_sum_processor import SimpleSumProcessor
from skywing.mid.sonata_processor import SONATAProcessor
from skywing.mid.sum_processor import SumProcessor
from skywing.mid.variance_processor import VarianceProcessor

PROCESSOR_OPTIONS = {
    "ADMM": ADMMProcessor,
    "COLA": COLAProcessor,
    "Count": CountProcessor,
    "Jacobi": JacobiProcessor,
    "Max": MaxProcessor,
    "Min": MinProcessor,
    "PushSum": PushSumProcessor,
    "SGD": SGDProcessor,
    "SimpleSum": SimpleSumProcessor,
    "SONATA": SONATAProcessor,
    "Sum": SumProcessor,
    "Variance": VarianceProcessor,
}


def main():
    # Parse the command line generated by the driver and generate the kwargs dictionary
    args = parse_driver_command_line()
    kwargs = argparse_list_to_kwargs(args.kwargs)
    try:
        processor = kwargs["processor"]
    except KeyError as err:
        raise ValueError(
            "Pass the desired processor as '--kwargs processor=<processor>'"
        ) from err
    # Number of data updates (0 corresponds to a single data point)
    num_data_updates = kwargs.get("num_data_updates", 3)
    # How often to update the data (in the case of a single
    # data point, update_freq is the total runtime)
    update_freq = kwargs.get("update_freq", 2.0)
    # How often to print current data/result to screen
    print_freq = kwargs.get("print_freq", 0.5)
    # The maximum staggering between agents, that is the
    # time between when the first agent starts and the last
    # agent starts (needed to ensure results are read at the
    # appropriate time between data updates).
    max_stagger = kwargs.get("max_stagger", 0.1)

    # Get the data_type, data_file, and output_file, if provided
    data_type = kwargs.get("data_type", "scalar")
    data_file = kwargs.get("data_file", None)
    output_dir = kwargs.get("output_dir", None)
    output_file = None
    if output_dir:
        output_file = os.path.join(output_dir, f"output_{args.agent_id}.npy")

    # Read or generate data
    if data_type in ["scalar", "vector", "matrix"]:
        if data_file:
            data_loader = CSVDataLoader(data_file, args.agent_id)
        else:
            if data_type == "scalar":
                data_loader = RandomScalarLoader()
            elif data_type == "vector":
                data_loader = RandomVectorLoader(5)
            elif data_type == "matrix":
                data_loader = RandomMatrixLoader(2, 2)
    elif data_type == "linear_system":
        if data_file:
            data_loader = LinearSystemDataLoader(data_file, args.agent_id)
            row_partition, col_partition = data_loader.get_partitions()
        else:
            _A, _b, _x, row_partition, col_partition = matrix_gen()

            def random_linear_system_data_loader():
                A, b, _x, _row_partition, _col_partition = matrix_gen()
                return (A, b)

            data_loader = random_linear_system_data_loader

        # WM: todo - try to avoid the need for K, size of the collective, below
        kwargs["K"] = len(col_partition)
    else:
        raise ValueError(
            f"Unknown data_type '{data_type}'. Available options: scalar, matrix."
        )
    data = data_loader()

    # Add K, and N_k, the collective size and neighborhood size
    # WM: todo - this is a potential point of future failure if we change the
    # variable name or add new processors with a conflicting name... ultimately
    # this should be discoverable automatically within the processor...
    kwargs["N_k"] = len(args.nbr_ports)

    # Add unique_id (used for SimpleSum)
    # WM: todo - will probably eliminate SimpleSum in favor of something more
    # robust in the future and can remove this
    kwargs["unique_id"] = f"agent{args.agent_id}"

    # Create the Skywing agent
    skywing_agent = create_skywing_agent(
        args.address,
        args.port,
        args.nbr_addresses,
        args.nbr_ports,
        args.test_async,
    )

    # Create the Skywing processor and iteration
    try:
        processor_type = PROCESSOR_OPTIONS[processor]
    except KeyError as err:
        available = ", ".join(PROCESSOR_OPTIONS.keys())
        raise ValueError(
            f"Unknown processor '{processor}'. Available options: {available}"
        ) from err
    skywing_processor = processor_type(data, **kwargs)
    skywing_iteration = Iteration(skywing_processor, skywing_agent)
    skywing_iteration.launch()

    # Ensure numpy writes will not wrap lines
    np.set_printoptions(linewidth=1000000)

    # Initialize timers, counters, and results list
    t_now = time.monotonic()
    t_next_print = t_now + print_freq
    t_next_update = t_now + update_freq
    t_next_result = t_now + update_freq - max_stagger
    update_cnt = 0
    print_cnt = 0
    all_results = []

    # Main execution loop: continue until the requested number of data updates
    while 1:
        # Sleep until next event
        t_next_event = min(t_next_print, t_next_update, t_next_result)
        time.sleep(t_next_event - t_now)
        t_now = time.monotonic()
        # Print current local data and iteration result every print_freq seconds
        if t_now >= t_next_print:
            result = skywing_iteration.query()
            print(f"On call {print_cnt}")
            print(f"   Data: {data}")
            print(f"   Result: {result}")
            print_cnt += 1
            t_next_print = t_now + print_freq
        # Update the local data every update_freq seconds
        if t_now >= t_next_update:
            update_cnt += 1
            if update_cnt > num_data_updates:
                break
            data = data_loader()
            skywing_iteration.update_data(data)
            t_next_update = t_now + update_freq
        # Save the iteration result for each data update every update_freq
        # seconds max_stagger seconds before the data gets updated
        if t_now >= t_next_result:
            result = skywing_iteration.query()
            all_results.append(result)
            t_next_result = t_now + update_freq

    if __debug__:
        logger.debug(
            f"Number of messages received from each tag: {skywing_iteration.num_recvs}"
        )

    # Save output to file
    if output_file:
        all_results = np.array(all_results)
        np.save(output_file, all_results)


if __name__ == "__main__":
    main()
