import time

from skywing.drivers.utils.agent_utils import create_skywing_agent
from skywing.drivers.utils.argparse_utils import (
    argparse_list_to_kwargs,
    parse_driver_command_line,
)
from skywing.drivers.utils.data_loaders import LinearSystemDataLoader
from skywing.mid.admm_processor import ADMMProcessor
from skywing.mid.cola_processor import COLAProcessor
from skywing.mid.cpp_iteration import CppIteration_PythonProc
from skywing.mid.iteration import Iteration
from skywing.mid.jacobi_processor import JacobiProcessor
from skywing.mid.sgd_processor import SGDProcessor
from skywing.mid.sonata_processor import SONATAProcessor

PROCESSOR_OPTIONS = {
    "ADMM": ADMMProcessor,
    "COLA": COLAProcessor,
    "Jacobi": JacobiProcessor,
    "SGD": SGDProcessor,
    "SONATA": SONATAProcessor,
}

if __name__ == "__main__":
    # Parse the command line generated by the driver and generate the kwargs dictionary
    args = parse_driver_command_line()
    kwargs = argparse_list_to_kwargs(args.kwargs)

    # Get the algorithm and output_dir from kwargs
    algorithm = kwargs["algorithm"]
    output_dir = kwargs["output_dir"]

    # Read in the global problem info
    data_loader = LinearSystemDataLoader(output_dir, args.agent_id)
    A_local, b_local = data_loader()
    row_partition, col_partition = data_loader.get_partitions()

    # Pass row_partition, col_partition, and history_dir as kwargs to the algorithm
    kwargs["row_partition"] = row_partition[args.agent_id]
    kwargs["col_partition"] = col_partition[args.agent_id]
    kwargs["history_dir"] = output_dir

    # Convert lam from str to float
    if kwargs.get("lam") is not None:
        kwargs["lam"] = float(kwargs["lam"])

    # Pass the collective size, K, and neighborhood size, N_k
    # WM: todo - would be nice not to need to have to do this this way
    kwargs["K"] = len(row_partition)
    kwargs["N_k"] = len(args.nbr_ports)

    # Setup the agent
    agent = create_skywing_agent(
        args.address,
        args.port,
        args.nbr_addresses,
        args.nbr_ports,
        args.test_async,
        args.backend,
    )

    # Setup and launch the iteration, then wait for completion
    try:
        processor_type = PROCESSOR_OPTIONS[algorithm]
    except KeyError as err:
        available = ", ".join(PROCESSOR_OPTIONS.keys())
        raise ValueError(
            f"Unknown algorithm '{algorithm}'. Available options: {available}"
        ) from err

    # WM: todo - remove cpp backend when the time comes
    if args.backend == "cpp":
        iteration = CppIteration_PythonProc(processor_type, agent)
        iteration.launch((A_local, b_local), **kwargs)
        iteration.wait()
    else:
        # WM: todo - I have to pass the agent as a kwarg below
        # AND I'm fudging a unique_id in order for the history_dir stuff to work...
        # This all used to happen automatically because the processor class
        # was constructed inside the old CppIteration_PythonProc initialization.
        # Now that the processor is constructed on its own, outside, the agent
        # and unique_id are not automatically added... This is all terrible, but
        # it's just for the history_dir stuff, and that usecase is basically
        # limited to just here... so fine for now. But this deserves further
        # refactor. Note that combining the processor and iteration classes
        # into one thing would make this all go away and be a lot more sensible.
        processor = processor_type(
            (A_local, b_local), agent=agent, unique_id=0, **kwargs
        )
        iteration = Iteration(processor, agent)
        iteration.launch()
        # WM: todo - merge the wait() functionality
        time.sleep(kwargs.get("max_time", 10))
