# This Makefile has no targets.  Its purpose is to be included by
# src/test/Makefile and src/ns3/Makefile

#-------------------------- Skynet project variables ---------------------------
SKYNET_INCLUDE_DIR = $(SKYNET_DIR)/include
SKYNET_LIBS = pthread
SKYNET_CXX_FLAGS = -Wall -Werror -std=c++14
SKYNET_CPP_FLAGS = -MMD -MP
CXX ?= g++
RM ?= rm -f
#-------------------------------------------------------------------------------
